import re


BASE_DOMAIN = "cloud-universe.anycubic.com"
AUTH_DOMAIN = "uc.makeronline.com"

PUBLIC_API_ENDPOINT = "p/p/workbench/api"

REX_JS_FILE = re.compile(r'src="(/js/app\.[^.]+\.js)"')
# REX_CLIENT_ID = re.compile(r',clientId:"([^"]+)",')
# REX_APP_ID = re.compile(r',appid:"([^"]+)",')
REX_CLIENT_ID = re.compile(r'\'(?!getEl)([a-zA-Z0-9]{20})\'')
REX_APP_ID = re.compile(r'(?<!:)\'([a-zA-Z0-9]{32})\'')
REX_APP_VERSION = re.compile(r'version["\']?:["\']([^"\']+)["\'],')
REX_APP_SECRET = re.compile(r'appSecret["\']?:["\']([^"\']+)["\'],')
REX_GCODE_EXT = re.compile(r'\.gcode$')

DEFAULT_USER_AGENT = (
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 '
    'Safari/537.36'
)

AC_KNOWN_CID = '672efcd4ec11a66c8513'
# AC_KNOWN_CID = 'ca4c8416cced85a1dc02'
AC_KNOWN_AID = 'f9b3528877c94d5c9c5af32245db46ef'
AC_KNOWN_VID = '1.0.0'
AC_KNOWN_SEC = '0cf75926606049a3937f56b0373b99fb'

COMMAND_ID_CAMERA_OPEN = 1001
COMMAND_ID_MULTI_COLOR_BOX_AUTO_FEED = 1212
COMMAND_ID_MULTI_COLOR_BOX_DRY = 1207
COMMAND_ID_MULTI_COLOR_BOX_SET_SLOT = 1211
COMMAND_ID_STOP_PRINT = 4
COMMAND_ID_STOP_PRINT_FORCE = 44
COMMAND_ID_LIST_LOCAL_FILES = 103
COMMAND_ID_START_PRINT = 1

FUNCTION_TYPE_ID_AXLE_MOVEMENT = 1
FUNCTION_TYPE_ID_FILE_MANAGER = 2
FUNCTION_TYPE_ID_EXPOSURE_TEST = 3
FUNCTION_TYPE_ID_LCD_PEER_VIDEO = 7
FUNCTION_TYPE_ID_FDM_AXIS_MOVE = 13
FUNCTION_TYPE_ID_FDM_PEER_VIDEO = 22
FUNCTION_TYPE_ID_DEVICE_STARTUP_SELF_TEST = 26
FUNCTION_TYPE_ID_PRINT_STARTUP_SELF_TEST = 27
FUNCTION_TYPE_ID_AUTOMATIC_OPERATION = 28
FUNCTION_TYPE_ID_RESIDUE_CLEAN = 29
FUNCTION_TYPE_ID_NOVICE_GUIDE = 30
FUNCTION_TYPE_ID_RELEASE_FILM = 31
FUNCTION_TYPE_ID_TASK_MODE = 32
FUNCTION_TYPE_ID_LCD_INTELLIGENT_MATERIALS_BOX = 33
FUNCTION_TYPE_ID_LCD_AUTO_OUT_IN_MATERIALS = 34
FUNCTION_TYPE_ID_M7PRO_AUTOMATIC_OPERATION = 35
FUNCTION_TYPE_ID_MULTI_COLOR_BOX = 2006
